name 'brocadevtm'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures brocadevtm'
long_description 'Installs/Configures brocadevtm'
version '0.1.161'
